Slynnex/front-banco

- package-lock.json
- package.json
- src/assets/Loader.js
- src/index.js
- src/pages/Executives.js
- src/styles/Loader.css
- src/styles/executives.css
> [IMP] executive crud done

- src/App.js
- src/context/Denominations/DenominationsContext.js
- src/context/Denominations/denominationsDataContext.js
- src/pages/Denominations/Denominations.js
- src/pages/Denominations/ModalDenominations.js
> Denominations completed

- src/App.js
- src/context/CreditDetails/CreditDetailsContext.js
- src/context/CreditDetails/creditDetailsDataContext.js
- src/context/Interests/InterestsContext.js
- src/context/Interests/interestsDataContext.js
- src/pages/CreditDetails/CreditDetails.js
- src/pages/CreditDetails/ModalCreditDetails.js
- src/pages/Interests/Interests.js
- src/pages/Interests/ModalInterests.js
- src/pages/Login.js
- src/styles/login.css
-make crud for credit details and interests
-make some changes in login page
> [IMP] creditdetails and interest crud

- src/pages/Login.js
> [IMP] change login design

- src/pages/PositionArea/ModalArea.js
- src/pages/PositionArea/ModalPosition.js
- src/pages/PositionArea/PositionArea.js
> Validation of Positions and Areas completed #30

- src/context/Cuts/CutsContext.js
- src/pages/Cuts/Cuts.js
- src/pages/Cuts/ModalCuts.js
This pull request includes the error handling in the Cuts page
> Errors validation of cuts

- package-lock.json
- package.json
- src/components/show_info/Show_info.js
- src/pages/Dashboard.js
> [IMP] charts

- src/pages/Concepts/Concepts.js
- src/pages/Concepts/ModalConcepts.js
Validation of Concepts completed and some console commented
> validation of concepts completed

- src/context/Transactions/TransactionsContext.js
- src/pages/Dashboard.js
- src/pages/Transactions/Transactions.js
> [IMP] filter transactions

- src/context/Clients/ClientsContext.js
- src/pages/Clients/Clients.js
- src/pages/Clients/TableClient.js
make filter to clients by full name
> [IMP] filter clients by full name

- src/components/show_info/Show_info.js
- src/context/Transactions/TransactionsContext.js
- src/pages/Clients/Clients.js
> [FIX] filters

- src/pages/Interests/Interests.js
- src/pages/Interests/ModalInterests.js
Validation and modifications of title, descriptions
> Validate interests#55 pr

- src/pages/CreditDetails/CreditDetails.js
- src/pages/CreditDetails/ModalCreditDetails.js
Validation of Credit Details #64 completed
> Validation of Creddit Details#64

- src/pages/Concepts/Concepts.js
- src/pages/Concepts/ModalConcepts.js
removed button edit and delete, finally corrections when validating
> Concepts fixed

- src/pages/Transactions/Transactions.js
- add executive name to transaction table
- correct date attribute on transactions table
> correct info to transaction table

- src/pages/Concepts/Concepts.js
- src/pages/Concepts/ModalConceptsDescription.js
Create model to show information about concepts v1
> Fix concepts#73 pr

- src/pages/Denominations/Denominations.js
Removed button create, update and delete #77
> Fix denominations completed #77

- src/pages/Concepts/Concepts.js
> Fix Concepts #80

- src/components/dashboard/DashboardSidebar.js
- src/pages/Dashboard.js
- src/pages/Login.js
This pull request includes the fix of Login functions and the correct redirection to each case
> Fix login#69 pr

- src/pages/Dashboard.js
- src/styles/Loader.css
debtors and replacements charts
> [IMP] new reports

- src/components/dashboard/UserRoutes.js
> Change Icons #103 completed
